### ISSUE TITLE
How to assemble fCal3 phantom

### ISSUE THREAD

**Issue by timirbarua** [PlusToolkit/PlusModelCatalog#7]
I am building a phantom for ultrasound calibration. But confuse about which one is better between glue and screw-nuts for joining the phantom pieces. Although I prefer screw nuts but have no idea about configuration of screw-nuts for perklab fcal3.1 phantom. If anybody has any idea which one is convenient and if screw-nuts please put a link for detail information. Thanks in advance.

**Comment by ungi** [comment]
For calibration, your primary goal is to collect calibration points as close to the corners of the image as possible. So, your tracked calibration phantom (either N-wires or stylus tip) needs to be as close to the corners of the image as possible. I would only use fCal phantom if you have no way to use a tracked stylus to collect calibration points. E.g. you need to clip on your tracker for every procedure, you cannot clip in the same position, and you need to maintain the tracked probe sterile. Otherwise, I would just use a tracked stylus and point at the image corners with it.

**Comment by timirbarua** [comment]
![IMG_20200402_113636](https://user-images.githubusercontent.com/62999365/78233817-9895d100-74d6-11ea-8ca1-7686690aecd1.jpg)
I provided the picture of phantom pieces. Could you tell me how can I attach those pieces?

**Comment by lassoan** [comment]
The phantom was designed to be assembled with screw-nuts. This model shows how to put the pieces together: https://github.com/PlusToolkit/PlusModelCatalog/blob/master/fCalPhantom/fCal_3/fCal_3.1.stl
